#!/bin/bash

# android
import_wifi_profile() {
    # adb shell "am start -n com.steinwurf.adbjoinwifi/.MainActivity -e ssid $ssid" # https://github.com/steinwurf/adb-join-wifi
    adb shell "am start -n com.adbwifisettingsmanager/.WifiSettingsManagerActivity --esn newConnection -e ssid $(printf '%q' "$1")" # https://github.com/pr4bh4sh/adb-wifi-setting-manager
}

import_wifi_profile "WiFi_Chefexpress"
import_wifi_profile "WiFi Frecciarossa"
import_wifi_profile "WiFi Frecciargento"
import_wifi_profile "WendysWifi"
import_wifi_profile "Wawa WiFi"
import_wifi_profile "Walmartwifi"
import_wifi_profile "Telstra"
import_wifi_profile "Taronga Guest WiFi"
import_wifi_profile "Sydney Tower - Guest"
import_wifi_profile "SWP_Lounges_Wifi"
import_wifi_profile "Starhotels"
import_wifi_profile "Starbucks WiFi"
import_wifi_profile "SolenadFreeWIFI4ALL"
import_wifi_profile "Smashburger Guest"
import_wifi_profile "skynetglobal"
import_wifi_profile "Shangri-La"
import_wifi_profile "Scenic World Free Wifi"
import_wifi_profile "Rydges World Square"
import_wifi_profile "RhB-FREE"
import_wifi_profile "QF-Guest"
import_wifi_profile "Portaleregionale"
import_wifi_profile "PAL_Wi-Fi"
import_wifi_profile "OperaHouse_FreeWiFi"
import_wifi_profile "OnAir"
import_wifi_profile "Olive Garden Guest"
import_wifi_profile "My Autogrill WI-FI"
import_wifi_profile "merz-gast"
import_wifi_profile "Merlin_Guest"
import_wifi_profile "McDonald's Free WiFi"
import_wifi_profile "Max's WiFi"
import_wifi_profile "Maccas Free Wi-fi"
import_wifi_profile "KFC Free Wifi"
import_wifi_profile "InfoTrainment"
import_wifi_profile "IBIS"
import_wifi_profile "Hungry Jack's FREE WiFi"
import_wifi_profile "hideaway "
import_wifi_profile "H&M Free WiFi"
import_wifi_profile "Grill'd Guest"
import_wifi_profile "Glowworm Caves Guest"
import_wifi_profile "FreeWiFi@SYD"
import_wifi_profile "FreeWiFi-NARITA(2.4G)"
import_wifi_profile "FreeWiFi-NARITA"
import_wifi_profile "FreeWiFi-NARITA-main(5G)"
import_wifi_profile "FreeMSGWIFI"
import_wifi_profile "Free_WiFi_GVA"
import_wifi_profile "Free WiFi"
import_wifi_profile "Free Telstra Wi-Fi"
import_wifi_profile "Free Skyline Internet"
import_wifi_profile "Fountains"
import_wifi_profile "EmiliaRomagnaWiFi wifiprivacy.it"
import_wifi_profile "Edelweiss"
import_wifi_profile "DIHDXB"
import_wifi_profile "digitalelpaso"
import_wifi_profile "CP WIFI"
import_wifi_profile "ConvergeFreeWifi_NAIAT3_5G"
import_wifi_profile "Comune di Tirano WiFi Free"
import_wifi_profile "ClientScape"
import_wifi_profile "CircuitLaneFreeWIFI4ALL"
import_wifi_profile "CBP_GUEST"
import_wifi_profile "BoldynWiFi"
import_wifi_profile "Boingo Hotspot"
import_wifi_profile "Auckland Airport"
import_wifi_profile "Atrium"
import_wifi_profile "Apple Store"
import_wifi_profile "Apple Demo"
import_wifi_profile "Animo Student"
import_wifi_profile "Animo Connect"
import_wifi_profile "ACCOR"
import_wifi_profile "#Wifi@Jewel"
import_wifi_profile "#WiFi@Changi"
import_wifi_profile "#Guest WiFi"
import_wifi_profile "#GigaSmartWiFi"
import_wifi_profile "#DXB Free WiFi"
import_wifi_profile "@WiFi UAE from du"
import_wifi_profile "@SOMOFreeWiFi"
import_wifi_profile "@NAIAT3FreeWIFI4ALL"
import_wifi_profile "@EVIAFreeWiFi"
import_wifi_profile "@Dubai Mall by EMAAR"
import_wifi_profile "_WorldSquareFreeWifi_"
import_wifi_profile "_FREE Smart WiFi @NAIA3"
import_wifi_profile "_Free JFK WiFi"
import_wifi_profile "_Free EWR Wifi"
import_wifi_profile "_DarlingSquareFreeWifi_"
